name: Update readme.io documentation
on:
  push:
    branches:
      - main
jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update readme.io documentation
        uses: apivideo/readmeio-document-sync-action@1.0
        with:
          document-slug: nodejs-api-client
          markdown-file-path: README.md
          readme-io-api-key: ${{ secrets.README_IO_API_KEY }}
          make-relative-links-absolute: true
   